export const sentenceBank = {
  easy: {
    short: [
      "A bola rola.",
      "O gato mia.",
      "A fada voa.",
      "O pato nada.",
      "A vaca muge.",
      "O sapo pula.",
      "A lua brilha.",
      "O sol aquece.",
      "A mala abre.",
      "O bebe ri.",
      "A pipa sobe.",
      "O dado caiu.",
      "A mesa gira.",
      "O lobo uiva.",
      "A mosca voa.",
      "O sino toca.",
      "A roda gira.",
      "O peixe nada.",
      "A folha cai.",
      "O galo canta.",
      "A neve some.",
      "O vento sopra.",
      "A abelha zumbe.",
      "O rato corre.",
      "A nuvem passa.",
      "O barco boia.",
      "A vovó fala.",
      "O menino sorri.",
      "A menina pula.",
      "O trem apita.",
      "A cama chama.",
      "O gelo derrete.",
      "A gota pinga.",
      "O porco grunhe.",
      "A planta cresce.",
      "O circo chegou.",
      "A blusa seca.",
      "O bolo cresce.",
      "A canoa anda.",
      "O fogo esquenta.",
      "A raposa corre.",
      "O polvo nada.",
      "A boneca caiu.",
      "O leao ruge.",
      "A janela abre.",
      "O balao sobe.",
      "A areia brilha.",
      "O coelho salta.",
      "A estrela pisca.",
      "O cabrito berra.",
    ],
    long: [
      "A bola azul rola no chao.",
      "O gato preto dorme no sofa.",
      "A fada boa voa no ceu.",
      "O pato nada no lago raso.",
      "A vaca branca come no pasto.",
      "O sapo verde pula na lama.",
      "A pipa vermelha sobe no vento.",
      "O bebe pequeno bate palma feliz.",
      "A lua clara brilha sobre o mar.",
      "O sol forte aquece toda a areia.",
      "A mesa redonda fica perto da porta.",
      "O rato cinza corre atras do queijo.",
      "A abelha amarela pousa na flor.",
      "O peixe dourado nada no aquario.",
      "A menina alegre gira com a saia.",
      "O menino esperto monta no cavalo.",
      "A roda grande gira na ladeira.",
      "O barco branco boia perto da ponte.",
      "A folha seca cai no jardim.",
      "O galo alto canta no terreiro cedo.",
      "A estrela clara aparece no ceu escuro.",
      "O trem longo apita perto da estacao.",
      "A boneca nova dorme na cama rosa.",
      "O leao forte ruge atras da pedra.",
      "A canoa leve passa no rio calmo.",
      "O bolo fofo cresce dentro do forno.",
      "A planta verde cresce com agua limpa.",
      "O fogo quente esquenta a panela.",
      "A areia fina brilha na praia limpa.",
      "O coelho branco salta no quintal.",
      "A janela aberta deixa o vento entrar.",
      "O balao colorido sobe bem devagar.",
      "A nuvem branca cobre parte do sol.",
      "O cabrito pequeno berra no curral.",
      "A raposa ligeira corre pelo mato.",
      "O polvo macio nada no mar fundo.",
      "A blusa azul seca no varal.",
      "O gelo frio derrete no copo.",
      "A gota clara pinga sobre a folha.",
      "O sino da igreja toca de manha.",
      "A mala grande fica perto da cama.",
      "O dado vermelho caiu sob a mesa.",
      "A mosca pequena voa pela sala.",
      "O lobo cinza uiva perto do monte.",
      "A vovo conta historia antes do sono.",
      "O porco gordo corre no chiqueiro.",
      "A neve fria some com o sol.",
      "O vento leve sopra na varanda.",
      "A roda do carro gira na rua.",
      "O circo alegre chegou na cidade.",
    ],
  },
  medium: {
    short: [
      "A menina canta feliz.",
      "O coelho corre rapido.",
      "A janela fica aberta.",
      "O menino lava a mao.",
      "A abelha pousa na flor.",
      "O cavalo bebe agua.",
      "A familia janta cedo.",
      "O cachorro abana o rabo.",
      "A escola abriu cedo.",
      "O palhaco contou piada.",
      "A arara gritou alto.",
      "O caderno caiu no chao.",
      "A professora sorriu contente.",
      "O jardineiro cortou a grama.",
      "A borboleta mudou de flor.",
      "O carteiro chegou agora.",
      "A cozinheira mexeu a sopa.",
      "O pintinho seguiu a galinha.",
      "A campainha tocou duas vezes.",
      "O aluno guardou o livro.",
      "A formiga entrou na toca.",
      "O macaco subiu depressa.",
      "A cadeira ficou torta.",
      "O padeiro vendeu pao.",
      "A lanterna iluminou tudo.",
      "O bombeiro fechou a mangueira.",
      "A tesoura cortou papel.",
      "O piloto olhou a pista.",
      "A artista pintou flores.",
      "O zelador abriu o portao.",
      "A mochila ficou pesada.",
      "O sapateiro limpou o sapato.",
      "A costureira mediu o pano.",
      "O peixinho sumiu da pedra.",
      "A historia ficou engraçada.",
      "O menino chutou a bola.",
      "A menina penteou o cabelo.",
      "O cachorro latiu na rua.",
      "A torneira pingou a noite.",
      "O feirante vendeu banana.",
      "A baba ninou o bebe.",
      "O artista tocou violao.",
      "A joaninha abriu as asas.",
      "O trator puxou o carro.",
      "A sereia cantou baixinho.",
      "O passarinho bebeu agua.",
      "A pipoca estourou depressa.",
      "O relogio marcou sete.",
      "A menina leu em voz alta.",
      "O foguete cortou o ceu.",
    ],
    long: [
      "A menina canta baixinho perto da mamae.",
      "O coelho branco corre no jardim de casa.",
      "O menino lava a mao antes do lanche.",
      "A abelha pequena pousa na flor amarela.",
      "O cavalo castanho bebe agua no balde.",
      "A janela da sala fica aberta de manha.",
      "A familia janta reunida depois da brincadeira.",
      "O cachorro alegre abana o rabo no quintal.",
      "A professora sorriu quando a turma terminou.",
      "O jardineiro cortou a grama perto do muro.",
      "A borboleta colorida mudou de flor no jardim.",
      "O carteiro chegou cedo com cartas e revistas.",
      "A cozinheira mexeu a sopa com cuidado.",
      "O pintinho amarelo seguiu a galinha pela fazenda.",
      "A campainha tocou duas vezes na entrada.",
      "O aluno guardou o livro dentro da mochila.",
      "A formiga pequena entrou na toca depressa.",
      "O macaco esperto subiu rapido na arvore.",
      "A cadeira de madeira ficou torta ontem.",
      "O padeiro vendeu pao quente logo cedo.",
      "A lanterna forte iluminou todo o corredor.",
      "O bombeiro fechou a mangueira depois da agua.",
      "A tesoura nova cortou o papel colorido.",
      "O piloto atento olhou a pista molhada.",
      "A artista pintou flores grandes na parede.",
      "O zelador abriu o portao antes da aula.",
      "A mochila azul ficou pesada com os cadernos.",
      "O sapateiro limpou o sapato com escova.",
      "A costureira mediu o pano sobre a mesa.",
      "O peixinho laranja sumiu atras da pedra.",
      "A historia engraçada fez todos rirem juntos.",
      "O menino chutou a bola para o gol.",
      "A menina penteou o cabelo antes da festa.",
      "O cachorro latiu quando ouviu passos no patio.",
      "A torneira pingou a noite toda na cozinha.",
      "O feirante vendeu banana madura na esquina.",
      "A baba ninou o bebe no quarto claro.",
      "O artista tocou violao durante a apresentacao.",
      "A joaninha abriu as asas sobre a folha.",
      "O trator puxou o carro preso na lama.",
      "A sereia cantou baixinho perto das pedras.",
      "O passarinho bebeu agua da fonte pequena.",
      "A pipoca estourou depressa dentro da panela.",
      "O relogio marcou sete horas em ponto.",
      "A menina leu a historia em voz alta.",
      "O foguete cortou o ceu escuro da noite.",
      "A arara gritou alto no galho mais alto.",
      "O caderno caiu no chao da sala.",
      "A escola abriu cedo para a reuniao.",
      "O palhaco contou piada no meio do show.",
    ],
  },
  hard: {
    short: [
      "A professora contou uma historia.",
      "O passarinho fez ninho na arvore.",
      "A formiga carregou uma folha.",
      "O bombeiro apagou o fogo.",
      "A familia saiu para passear.",
      "O pirata achou um mapa.",
      "A astronauta olhou pela janela.",
      "O cientista misturou liquidos coloridos.",
      "A diretora chamou a turma.",
      "O violinista afinou o instrumento.",
      "A cozinheira preparou um banquete.",
      "O fazendeiro consertou a cerca.",
      "A bibliotecaria organizou os livros.",
      "O marinheiro avistou uma ilha.",
      "A costureira terminou o vestido.",
      "O explorador atravessou a floresta.",
      "A enfermeira cuidou do paciente.",
      "O motorista seguiu outro caminho.",
      "A escritora imaginou novos personagens.",
      "O jardineiro podou as roseiras.",
      "A pianista ensaiou por horas.",
      "O fotografo registrou a paisagem.",
      "A bailarina girou no palco.",
      "O pedreiro levantou a parede.",
      "A meteorologista observou as nuvens.",
      "O arqueologo limpou a estatua.",
      "A engenheira revisou o projeto.",
      "O pescador remendou a rede.",
      "A artesa pintou os vasos.",
      "O mensageiro entregou o pacote.",
      "A veterinaria examinou o filhote.",
      "O locutor anunciou o resultado.",
      "A aldeia celebrou a colheita.",
      "O escultor moldou a argila.",
      "A atriz decorou o roteiro.",
      "O estudante resolveu o problema.",
      "A ceramista aqueceu o forno.",
      "O repórter entrevistou o atleta.",
      "A musicista criou uma melodia.",
      "O capitão orientou a tripulacao.",
      "A pesquisadora analisou os dados.",
      "O padeiro recheou os sonhos.",
      "A costureira alinhavou a barra.",
      "O nadador treinou pela manha.",
      "A rainha visitou o castelo.",
      "O garoto encontrou um enigma.",
      "A garota escreveu um poema.",
      "O foguista alimentou a caldeira.",
      "A turma montou um teatro.",
      "O professor explicou com paciencia.",
    ],
    long: [
      "A professora contou uma historia bonita para a turma.",
      "O passarinho fez ninho na arvore do quintal.",
      "A formiga carregou uma folha grande ate a toca.",
      "O bombeiro apagou o fogo com muita coragem.",
      "A familia saiu para passear no parque da cidade.",
      "O pirata achou um mapa velho dentro do bau.",
      "A astronauta olhou pela janela da nave silenciosa.",
      "O cientista misturou liquidos coloridos no laboratorio.",
      "A diretora chamou a turma para uma conversa.",
      "O violinista afinou o instrumento antes do concerto.",
      "A cozinheira preparou um banquete para os convidados.",
      "O fazendeiro consertou a cerca perto do celeiro.",
      "A bibliotecaria organizou os livros por assunto.",
      "O marinheiro avistou uma ilha depois da tempestade.",
      "A costureira terminou o vestido com muito capricho.",
      "O explorador atravessou a floresta com uma bussola.",
      "A enfermeira cuidou do paciente com delicadeza.",
      "O motorista seguiu outro caminho por causa da chuva.",
      "A escritora imaginou novos personagens para a aventura.",
      "O jardineiro podou as roseiras no fim da tarde.",
      "A pianista ensaiou por horas para o recital.",
      "O fotografo registrou a paisagem no alto da serra.",
      "A bailarina girou no palco durante a apresentacao.",
      "O pedreiro levantou a parede com muito cuidado.",
      "A meteorologista observou as nuvens antes da chuva.",
      "O arqueologo limpou a estatua encontrada nas ruinas.",
      "A engenheira revisou o projeto com toda a equipe.",
      "O pescador remendou a rede antes de sair.",
      "A artesa pintou os vasos com desenhos delicados.",
      "O mensageiro entregou o pacote no fim da tarde.",
      "A veterinaria examinou o filhote com atencao.",
      "O locutor anunciou o resultado para todo o estadio.",
      "A aldeia celebrou a colheita com musica e danca.",
      "O escultor moldou a argila ate formar um rosto.",
      "A atriz decorou o roteiro para a estreia.",
      "O estudante resolveu o problema usando outra estrategia.",
      "A ceramista aqueceu o forno antes da queima.",
      "O reporter entrevistou o atleta depois da prova.",
      "A musicista criou uma melodia suave no piano.",
      "O capitao orientou a tripulacao durante a viagem.",
      "A pesquisadora analisou os dados com paciencia.",
      "O padeiro recheou os sonhos com creme doce.",
      "A costureira alinhavou a barra antes de costurar.",
      "O nadador treinou pela manha antes do campeonato.",
      "A rainha visitou o castelo antigo da montanha.",
      "O garoto encontrou um enigma dentro do livro.",
      "A garota escreveu um poema sobre o mar.",
      "O foguista alimentou a caldeira com muito cuidado.",
      "A turma montou um teatro para a feira.",
      "O professor explicou a conta com muita paciencia.",
    ],
  },
};
